module Everything where

import Categories
import Monads
import Splits
import RestrictionCat
import RestrictionMaybe
import PartialMaps
import RestrictionDelay
import RestrictionPred
import Completeness
import Utilities
import Products
import Soundness
import MonicClasses
import RestrictionFunctors
import Categories.Pullbacks
import Categories.Sections
import Categories.Isos
import Categories.Epis
import Categories.Monos
import Categories.Idems
import Categories.Pullbacks.PullbacksLemmas
import Categories.Pullbacks.PastingLemmas
import Sets
import Stable
import ProductCats
import Totals
import Functors
import StrongFuns
import SplitRestCats
import Monads.Delay
import Monads.Kleisli
import Monads.EMAlgebras
import Monads.PredicatePart
import Monads.EMCat
import Monads.Maybe
